### ISSUE TITLE
setup.py doesn't work <python 3.6 as readme has unicode characters

### ISSUE THREAD

**Issue by Ultimation** [fitnr/convertdate#16]
```/usr/bin/python3.4 setup.py build '--executable=/usr/bin/python3.4 -s'
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "setup.py", line 13, in <module>
BUILDSTDERR:     readme = open('README.rst').read()
BUILDSTDERR:   File "/usr/lib64/python3.4/encodings/ascii.py", line 26, in decode
BUILDSTDERR:     return codecs.ascii_decode(input, self.errors)[0]
BUILDSTDERR: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 89: ordinal not in range(128)
```

**Comment by dlangille** [comment]
My solution when building for Python 3.6:

rm README.rst
touch README.rst

**Comment by dlangille** [comment]
Suggestion via IRC: probably it is utf-8 and not ascii, you could try adding   encoding="utf-8"    to that open()
